name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
  create:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]
        django-version: [2.2.*, 3.2.*]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      - name: install node and npm
        run: |
          sudo apt-get -yqq update && sudo apt-get install -yqq nodejs npm

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django==${{ matrix.django-version }}
          pip install poetry

      - name: install dependencies
        run: |
          poetry install

      - name: run tests
        run: |
          poetry run tox

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: install node & npm
        run: |
          sudo apt-get -yqq update && sudo apt-get install -yqq nodejs npm

      - name: install dependencies
        run: |
          poetry install

      - name: build
        run: |
          poetry build

      - name: publish
        run: |
          poetry publish
