name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
  create:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]
        django-version: [2.2.*, 3.2.*]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      - name: install node and npm
        run: |
          sudo apt-get -yqq update && sudo apt-get install -yqq nodejs npm

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: install dependencies
        run: |
          poetry install

      - name: downgrade django to matrix version
        run: |
          poetry run pip install django==${{ matrix.django-version }}

      - name: run testss
        run: |
          poetry run pytest -c tox-ghaction.ini

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: build
        run: |
          poetry build

      - name: publish test.pypi
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_TOKEN }}
          poetry publish -r testpypi

      - name: publish pypi
        run: |
          petry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish
